server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=task_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.web.resources.add-mappings=false

spring.mvc.resource.exception-on-no-resource=true

