ALTER TABLE tasks
    ALTER COLUMN due_date TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN completion_date TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ALTER COLUMN joining_date TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN joining_date SET NOT NULL,
    ALTER COLUMN resign_date TYPE TIMESTAMP WITH TIME ZONE; 